package chess_game.gui;

import javax.swing.DefaultListModel;
import javax.swing.JLabel;

public class BottomMenu extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public DefaultListModel killedPiecesListModel;
    public BottomMenu() {
        initComponents();
    }
    public JLabel getPlayersColorLBL() {
        return playersColorLBL;
    }

    public JLabel getTurnLBL() {
        return turnLBL;
    }

    public void setTurnLBL(JLabel turnLBL) {
        this.turnLBL = turnLBL;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        turnLBL = new javax.swing.JLabel();
        playersColorLBL = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout());

        turnLBL.setBackground(new java.awt.Color(13, 197, 197));
        turnLBL.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        turnLBL.setForeground(new java.awt.Color(255, 255, 0));
        turnLBL.setText("Your Turn");
        add(turnLBL);

        playersColorLBL.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        playersColorLBL.setText("TEAM:");
        add(playersColorLBL);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel playersColorLBL;
    private javax.swing.JLabel turnLBL;
    // End of variables declaration//GEN-END:variables
}
