package chess_game.gui;

import javax.swing.JButton;
import javax.swing.JLabel;

public class MainMenu extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public MainMenu() {
        initComponents();

    }

    public JButton getExitBTN() {
        return exitBTN;
    }

   
    public JLabel getInfoLBL() {
        return infoLBL;
    }

    public JButton getPlayBTN() {
        return playBTN;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        infoLBL = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 102));
        setLayout(new java.awt.BorderLayout());

        playBTN.setText("Search Match");
        playBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBTNActionPerformed(evt);
            }
        });
        add(playBTN, java.awt.BorderLayout.CENTER);

        exitBTN.setText("Exit");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });
        add(exitBTN, java.awt.BorderLayout.PAGE_START);

        infoLBL.setText("Matching");
        add(infoLBL, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    private void playBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playBTNActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBTN;
    private javax.swing.JLabel infoLBL;
    private javax.swing.JButton playBTN;
    // End of variables declaration//GEN-END:variables
}
